### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by rageandqq** [DavidGoldman/flash#1]
Got a live demo from the developer and it just wasn't working 
My phone is now bricked and won't start 
I'm typing this from a Kindle I purchased just to write his complaint

11/10 would try again for the lolz

**Comment by rageandqq** [comment]
Oh nvm I deleted the lock screen app and now it works 
5/10 now tho, novelty has worn off

**Comment by DavidGoldman** [comment]
2/10 would not use again.
